### ISSUE TITLE
Usage in async context

### ISSUE THREAD

**Issue by apiraino** [calvinbrown085/warp-prometheus#1]
Hi @calvinbrown085 , great to see this crate! :)

I had a cursory look and have one thought: currently the Prometheus crate is synchronous, so if I'm not wrong each action of pushing metrics to a Prometheus server would block one tokio thread, is that correct?
I would mention (maybe with an example?) how to use the crate in an async context like Warp until they (crate Prometheus) make it runnable in a tokio context.

(please fix my thinking if anything I wrote is incorrect!)

**Comment by calvinbrown085** [comment]
@apiraino You might be correct, im not as familiar with pushing metrics to prometheus, that would be good to look into though. I was trying to keep this crate just dependent on prometheus, and not so much how the user of the library is getting metrics to prometheus. This should work either way, push or scrape.

**Comment by apiraino** [comment]
hey thanks for your insights, makes totally sense. meanwhile I checked a bit the prometheus examples (like [this one](https://github.com/tikv/rust-prometheus/blob/1e7736f8bcac5600f787484262b7153af98f8345/examples/example_hyper.rs#L34)) and my (perhaps limited) understanding is that, in order to be non-blocking, the HTTP call to Prometheus should at at least wrapped in a new Tokio thread with `tokio::spawn` (running on the current executor) or on a new dedicated executor with its threadpool.

I'll play with it as my time allows, thanks for making me curious about the subject :)
